name: Generate PDF from Markdown

on:
  push:
    branches: [main]
    paths:
      - 'report/**'
      - '.github/workflows/generate-pdf.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive texlive-latex-extra


      - name: Convert Markdown to PDF
        run: |
          mkdir -p public
          pandoc report.md -o public/report.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
