name: VHDL Syntax Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-vhdl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GHDL
        run: |
          sudo apt update
          sudo apt install -y ghdl

      - name: Analyze VHDL files with GHDL
        run: |
          mkdir -p work
          for file in $(find . -name "*.vhd"); do
            echo "Analyzing $file"
            ghdl -a --workdir=work "$file"
          done
